/*
Math object

Willekeurig 1
Maak een variabele floatSpeed met een waarde van 10,4
Maak een variabele lowSpeed waarvan de waarde floatSpeed afgerond is naar beneden.
Maak een variabele highSpeed waarvan de waarde floatSpeed afgerond is naar boven.*/



/* thomas
   let oef2_1=Math.floor(Math.random()*50+50);
   let oef2_2=Math.floor(Math.random());
   //from 0 to 10.99 -> round down
   let oef2_3=Math.floor(Math.random()*11);
   console.log(oef2_1+" "+oef2_2+" "+oef2_3);*/


   let floatSpeed=10.4;
       lowSpeed= Math.floor(floatSpeed);
       highSpeed= Math.ceil(floatSpeed);
